theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: purple
  icon:
    logo: material/currency-btc
    favicon: assets/images/favicon.svg

site_name: 虚拟货币模拟盘交易记录
site_description: 个人虚拟货币模拟盘交易记录和分析
copyright: 2026 虚拟货币模拟盘交易记录

nav:
  - 首页: index.md


plugins:
  - search

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SEMHAQ/crypto_simulated_trading

